// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Q1.Models;

public partial class CourseAssignment
{
    public int CourseId { get; set; }

    public int InstructorId { get; set; }

    public DateOnly? AssignmentDate { get; set; }

    public virtual Course Course { get; set; }

    public virtual Instructor Instructor { get; set; }
}