// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Q1.Models;

public partial class Instructor
{
    public int InstructorId { get; set; }

    public string FullName { get; set; }

    public string Expertise { get; set; }

    public DateOnly? HireDate { get; set; }

    public virtual ICollection<CourseAssignment> CourseAssignments { get; set; } = new List<CourseAssignment>();
}